### ISSUE TITLE
"ui" testing

### ISSUE THREAD

**Issue by oli-obk** [davidbarsky/tracing-tree#20]
In rustc and clippy we're using the compiletest-rs framework for committing the output of programs (in that case error messages) to git so we see diffs in PRs and realize if we do accidental changes. It's not trivial to maintain (causes breakage every now and then, uses nightly, probably causes your CI time to go up significantly), but it's very powerful.

Alternatively we could just write tests that write to files that are commited if a specific env var is set and otherwise tests whether the files are the same (so on CI).

Are you interested in either framework for testing the rendered output?

**Comment by davidbarsky** [comment]
I wasn't successful in setting up compiletest in the past, but it seems really powerful. I'll happily accept a PR if you have one, nightly and all.
