### ISSUE TITLE
`with_verbose_entry`/`verbose_entry` seem to be ignored

### ISSUE THREAD

**Issue by matthewess** [davidbarsky/tracing-tree#23]
I noticed `tracing_tree` seemed to be logging a lot for functions i had decorated with `instrument`, like so:

```
synth{tm=App(Ann(Lambda(x, Var(x)), Forall(A, Forall(B, Arrow(Arrow(Var(A), Var(B)), Arrow(Var(A), Var(B)))))), Lambda(x, Var(x)))}
├─┐synth{tm=App(Ann(Lambda(x, Var(x)), Forall(A, Forall(B, Arrow(Arrow(Var(A), Var(B)), Arrow(Var(A), Var(B)))))), Lambda(x, Var(x)))}
│ └─┐synth{tm=Ann(Lambda(x, Var(x)), Forall(A, Forall(B, Arrow(Arrow(Var(A), Var(B)), Arrow(Var(A), Var(B))))))}
│   ├─┐synth{tm=Ann(Lambda(x, Var(x)), Forall(A, Forall(B, Arrow(Arrow(Var(A), Var(B)), Arrow(Var(A), Var(B))))))}
```

which corresponds to only a single nested recursive call, eg `synth` only gets called with each repeated set of arguments once.

I noticed that `verbose_entry` defaults to `false`, but it doesn't seem to be checked anywhere in the codebase, and thus *seems* to be a no-op. I imagine there should be some check [similar to this](https://github.com/davidbarsky/tracing-tree/blob/main/src/lib.rs#L385) added for `verbose_entry`?

**Comment by oli-cosmian** [comment]
oops, I indeed forgot to connect this flag.
