### ISSUE TITLE
tracing-tree and `Future::instrument` do not go well together

### ISSUE THREAD

**Issue by oli-cosmian** [davidbarsky/tracing-tree#25]
I just tried using `tracing-tree` on async-heavy code, and that gave me many many messages about spans being entered and exited, without anything actually happening. This is because `instrument` invokes `enter` every time the future is polled and `exit` whenever that poll is done.

So... what I'm wondering is whether we can somehow allow `tracing-tree` to be used on async code by only emitting messages on a span's `new_span` invocation and on its `on_close` invocation instead of `on_enter` and `on_exit`. I'm aware this is not "correct" from `tracing`'s `Span` model, since we'd be missing intermediate `enter` and `exit` invocations, but I'm not sure how else to do it without introducing more config flags and state.

**Comment by hawkw** [comment]
Wasn't the intention of the `verbose_entry` flag to control whether or not anything was logged for `enter`s?

Personally, this is why I generally advise most people who are formatting `tracing` data to not format enters and exits directly, but instead simply use them for determining the span contexts in which events, span creation, etc occur in. I _thought_ I advised against this crate printing every enter a while ago, but maybe I didn't actually. The point being, though, I definitely wouldn't consider it "not correct" to not print every enter and exit; in general, it's the behavior I would suggest.
