### ISSUE TITLE
Upgrade to tracing-subscriber 0.3

### ISSUE THREAD

**Issue by theduke** [davidbarsky/tracing-tree#36]
Tracing-subscriber 0.3 was released, would be great to see an upgrade here as well.

**Comment by davidbarsky** [comment]
yeah, i agree. tracing-tree uses a deprecated method in tracing-subscriber and their replacements seem to require foreknowledge as to whether the scope is an event or a span—otherwise, the formatting looks off. i haven't had the time (yet) to fix this.

**Comment by davidbarsky** [comment]
This was resolved in #40. I'll have a 0.2 release with those changes out shortly.

**Comment by theduke** [comment]
Great, thanks!
