### ISSUE TITLE
Please add text(s) of license(s)

### ISSUE THREAD

**Issue by krasimirgg** [davidbarsky/tracing-tree#37]
The license field in Cargo.toml indicates that this package is licensed under "MIT OR Apache-2.0". It's good to have the license(s) text(s) in the repository as well (and into the cargo package) so this work can be properly attributed downstream.

Just for completeness, https://github.com/gimli-rs/addr2line is an example of a similarly licensed package. It includes the texts in LICENSE-APACHE and LICENSE-MIT.

**Comment by davidbarsky** [comment]
That's reasonable! Feel free to open a PR for this, by the way—I'd be happy to release a change with this, especially if this is blocking you!

**Comment by krasimirgg** [comment]
Could you also please update [the minor version of this crate over at crates.io](https://crates.io/crates/tracing-tree/versions).

**Comment by davidbarsky** [comment]
Sorry for the delay—yeah, I'll push out a release.

**Comment by davidbarsky** [comment]
@krasimirgg sorry for the delay! it's out: https://github.com/davidbarsky/tracing-tree/releases/tag/v0.1.11

**Comment by krasimirgg** [comment]
This is great! Thank you @davidbarsky !
