### ISSUE TITLE
feature: Draw lines

### ISSUE THREAD

**Issue by hawkw** [davidbarsky/tracing-tree#4]
Right now, the tree hierarchy is expressed only with indentation. It would be nice to have the option to draw a line as well, using either ASCII characters like pipes and dashes, or Unicode box drawing characters. Ideally we would auto-detect whether the console supports Unicode, but it could probably start out as a config option.

**Comment by eddyb** [comment]
This is what the example in the README would look like with the approach I had back in the day, in some C++ codebase: [example-1](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/95bc5ff39460638d2bc998abb23c524e33ef7ca9/tracing-box-drawing-1) (GitHub's treatment of monospace still doesn't correctly handle unicode box-drawing, so I had to improvize)

Looking at it, this is probably slightly more readable: [example-2](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/95bc5ff39460638d2bc998abb23c524e33ef7ca9/tracing-box-drawing-2).

**Comment by eddyb** [comment]
Brought back the two-space indentation, now that it's clearer where it should go: [example-3](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/6c75bf462bf66cc271bc6c4ab6b4ae6313c5a973/tracing-box-drawing-3).

**Comment by eddyb** [comment]
Tried something slightly different: [example-4](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/6e550cd5038775f5da04bcb292376ebe0aaaf4f8/tracing-box-drawing-4) and then spent too much staring at https://en.wikipedia.org/wiki/Box_Drawing_(Unicode_block), resulting in [example-5](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/30893263cb8c655c402834ddcfc5036f285a3cef/tracing-box-drawing-5).

**Comment by eddyb** [comment]
@hawkw pointed me to the `tree` output, so I've come up with two variations based on it:
* [example-6](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/7cf24a8f9b119ddc2761e9475b1a2a8cc6e4e779/tracing-box-drawing-6) (compact)
* [example-7](https://gist.githubusercontent.com/eddyb/05a9490eb50396754cee14967c485567/raw/7cf24a8f9b119ddc2761e9475b1a2a8cc6e4e779/tracing-box-drawing-7) (extra empty lines after the end of each span)

**Comment by hawkw** [comment]
@eddyb I think example-7 is probably my favourite.

But, what do you think about adding a `-` after the `├` character for events, as well as spans? Like
```
╺━server{host="localhost", port=8080}
  ├-  0ms  INFO starting
  ├-300ms  INFO listening
  ┝━conn{peer_addr="82.9.9.9", port=42381}
  │ ├- 0ms DEBUG connected
  │ └-300ms DEBUG message received, length=2
  ┝━conn{peer_addr="8.8.8.8", port=18230}
  │ └-300ms DEBUG connected
  ┝━conn{peer_addr="82.9.9.9", port=42381}
  │ ├600ms  WARN weak encryption requested, algo="xor"
  │ ├901ms DEBUG response sent, length=8
  │ └901ms DEBUG disconnected
  ┝━conn{peer_addr="8.8.8.8", port=18230}
  │ ├-600ms DEBUG message received, length=5
  │ ├-901ms DEBUG response sent, length=8
  │ └-901ms DEBUG disconnected
  ├-1502ms  WARN internal error
  └-1502ms  INFO exit
```
This only uses one additional character of horizontal space, and the tree reads much more clearly IMO.

**Comment by hawkw** [comment]
I'm also a little iffy about using thicker lines for spans. How would it look if we got rid of the `┝━`, and just put a newline before and after each span to set them apart from events? I think we can be a bit more generous with vertical space than we can with horizontal space...

**Comment by eddyb** [comment]
Sure, but also note that you shouldn't combine box-drawing characters with regular pipes (`|`) or dashes (`-`) since they won't connect, you need to use the appropriate box-drawing character that looks like what you want.

**Comment by hawkw** [comment]
agh, you're right. imagine i used the right box drawing character above. :)

**Comment by hawkw** [comment]
Pretty sure #8 implemented this.
