### ISSUE TITLE
Subscriber: Debug

### ISSUE THREAD

**Issue by conradludgate** [davidbarsky/tracing-tree#45]
Is there any reason why the `HeirarchicalLayer` needs the `S: fmt::Debug` bound? The code doesn't seem to use it anywhere

**Comment by conradludgate** [comment]
Not directly, but it does make it harder to pair this layer with others that might not implement debug.

I think the debug requirement for Layer should be moved to the debug imply itself

**Comment by davidbarsky** [comment]
yeah, i'm not opposed to that change. i don't think that moving the debug implementation is a breaking change to a separate impl block, but i'll confirm.

**Comment by davidbarsky** [comment]
Resolved by #46.
