### ISSUE TITLE
`ansi_term` crate is not maintained

### ISSUE THREAD

**Issue by aaronbembenek-aws** [davidbarsky/tracing-tree#51]
The `ansi_term` crate is no longer maintained: https://rustsec.org/advisories/RUSTSEC-2021-0139

Would you consider replacing it with another library that is maintained, like [`yansi`](https://crates.io/crates/yansi) (which has similar APIs)?

~~I have a fork of `tracing-tree` using `yansi` and would be happy to open a PR.~~

**Comment by davidbarsky** [comment]
In [tracing-subscriber](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/) and [tracing-glog](https://docs.rs/tracing-glog/) we switched to using [nu-ansi-term](https://github.com/nushell/nu-ansi-term), so while I'd appreciate a PR to switch away from `ansi_term`, I think I'd prefer that we matched some of the other crates.

**Comment by davidbarsky** [comment]
I also didn't realize Kani was using tracing! it's flattering to be used by such a neat project!

**Comment by aaronbembenek-aws** [comment]
> In [tracing-subscriber](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/) and [tracing-glog](https://docs.rs/tracing-glog/) we switched to using [nu-ansi-term](https://github.com/nushell/nu-ansi-term), so while I'd appreciate a PR to switch away from `ansi_term`, I think I'd prefer that we matched some of the other crates.

That makes sense! I'll open a PR with `nu_ansi_term`.

**Comment by aaronbembenek-aws** [comment]
Thanks for merging that PR! Do you have a schedule for when the next release will be published to crates.io? We'd like to use that release once it's ready.
