### ISSUE TITLE
Publish updated release on crates.io?

### ISSUE THREAD

**Issue by aaronbembenek-aws** [davidbarsky/tracing-tree#53]
Would it be possible to publish a new release to crates.io, with the updated dependency from `ansi_term` to `nu_ansi_term`? We'd like to use that release once it's ready. Thank you!

**Comment by davidbarsky** [comment]
whoops, sorry! i think i saw you comment on the PR, but didn't too much.

(sorry, my employer had layoffs this week. i wasn't affected, but it was a bit stressful!)

**Comment by davidbarsky** [comment]
It's out: https://crates.io/crates/tracing-tree/0.2.2

**Comment by aaronbembenek-aws** [comment]
Thanks so much!

I'm sorry to hear about the layoffs/stress :(

**Comment by davidbarsky** [comment]
totally, and thanks :)
