### ISSUE TITLE
Writing to stderr

### ISSUE THREAD

**Issue by flodiebold** [davidbarsky/tracing-tree#9]
I think it'd be great to use tracing-tree in rust-analyzer (if only to display Chalk logs), but that's not possible as long as it writes to stdout (that's reserved for LSP communication). Could it just write to stderr instead, or alternatively be configurable?

**Comment by davidbarsky** [comment]
I can switch it to `stderr` and possibly introduce the `MakeWriter` from `tracing-subscriber` trait so this is customizable. Won't take much effort on my end; hold on.
